
<script>
    var INSERT_CODE = "<?= $_SESSION["INSERT_CODE"]=GUIDv4(); ?>";
    var UPDATE_CODE = "<?= $_SESSION["UPDATE_CODE"]=GUIDv4(); ?>";
    var DELETE_CODE = "<?= $_SESSION["DELETE_CODE"]=GUIDv4(); ?>";
    var MULTI_DELETE_CODE = "<?= $_SESSION["MULTI_DELETE_CODE"]=GUIDv4(); ?>";
    var ACTIVATE_CODE = "<?= $_SESSION["ACTIVATE_CODE"]=GUIDv4(); ?>";
    var DEACTIVATE_CODE = "<?= $_SESSION["DEACTIVATE_CODE"]=GUIDv4(); ?>";
	var ACTIVATE_TOPMENU_CODE = "<?= $_SESSION["ACTIVATE_TOPMENU_CODE"]=GUIDv4(); ?>";
    var DEACTIVATE_TOPMENU_CODE = "<?= $_SESSION["DEACTIVATE_TOPMENU_CODE"]=GUIDv4(); ?>"; 	
	var ACTIVATE_HASRESOURCE_CODE = "<?= $_SESSION["ACTIVATE_HASRESOURCE_CODE"]=GUIDv4(); ?>";
    var DEACTIVATE_HASRESOURCE_CODE = "<?= $_SESSION["DEACTIVATE_HASRESOURCE_CODE"]=GUIDv4(); ?>"; 	
	var ACTIVATE_PAYMENT_CODE = "<?= $_SESSION["ACTIVATE_PAYMENT_CODE"]=GUIDv4(); ?>";
    var DEACTIVATE_PAYMENT_CODE = "<?= $_SESSION["DEACTIVATE_PAYMENT_CODE"]=GUIDv4(); ?>"; 
	var CUSTOMIZE_CODE = "<?= $_SESSION["CUSTOMIZE_CODE"]=GUIDv4(); ?>"; 
	var UNCUSTOMIZE_CODE = "<?= $_SESSION["UNCUSTOMIZE_CODE"]=GUIDv4(); ?>"; 
	var GET_DATE_AND_PRICE_CODE = "<?= $_SESSION["GET_DATE_AND_PRICE_CODE"]=GUIDv4(); ?>";
    var GET_PRICE_CODE = "<?= $_SESSION["GET_PRICE_CODE"]=GUIDv4(); ?>"; 	
    var SEND_TO_SUBJECTS_CODE = "<?= $_SESSION["SEND_TO_SUBJECTS_CODE"]=GUIDv4(); ?>";
	var UPDATE_TO_SUBJECTS_CODE = "<?= $_SESSION["UPDATE_TO_SUBJECTS_CODE"]=GUIDv4(); ?>";
	var DELETE_TO_SUBJECTS_CODE = "<?= $_SESSION["DELETE_TO_SUBJECTS_CODE"]=GUIDv4(); ?>";
	var SEND_TO_ALL_SUBJECTS_CODE = "<?= $_SESSION["SEND_TO_ALL_SUBJECTS_CODE"]=GUIDv4(); ?>";
    var EDIT_CODE = "<?= $_SESSION["EDIT_CODE"]=GUIDv4(); ?>"; 
    var SET_UPLOAD_FOLDER_CODE = "<?= $_SESSION["SET_UPLOAD_FOLDER_CODE"]=GUIDv4(); ?>";
	var SEND_TO_TELEGRAM_CODE = "<?= $_SESSION["SEND_TO_TELEGRAM_CODE"]=GUIDv4(); ?>";
	var SEND_TO_REPORTAGE_CODE = "<?= $_SESSION["SEND_TO_REPORTAGE_CODE"]=GUIDv4(); ?>";
	var SET_GROUP_ACCESS_CODE = "<?= $_SESSION["SET_GROUP_ACCESS_CODE"]=GUIDv4(); ?>";
	var SET_CATEGORY_CODE = "<?= $_SESSION["SET_CATEGORY_CODE"]=GUIDv4(); ?>";
	var SET_USER_TYPE_CODE = "<?= $_SESSION["SET_USER_TYPE_CODE"]=GUIDv4(); ?>";
	var PASSWORD_CHANGE_CODE = "<?= $_SESSION["PASSWORD_CHANGE_CODE"]=GUIDv4(); ?>";
	var GET_CATEGORY_LIST_CODE = "<?= $_SESSION["GET_CATEGORY_LIST_CODE"]=GUIDv4(); ?>";
	var GET_SUBCATEGORY_LIST_CODE = "<?= $_SESSION["GET_SUBCATEGORY_LIST_CODE"]=GUIDv4(); ?>";
	var GET_CITY_LIST_CODE = "<?= $_SESSION["GET_CITY_LIST_CODE"]=GUIDv4(); ?>";
	var LISTING_CODE = "<?=$_SESSION["LISTING_CODE"]=GUIDv4(); ?>";
	var ACCEPT_REQUEST_CODE = "<?=$_SESSION["ACCEPT_REQUEST_CODE"]=GUIDv4(); ?>";
	var REJECT_REQUEST_CODE = "<?=$_SESSION["REJECT_REQUEST_CODE"]=GUIDv4(); ?>";
	var POST_IMAGE_UPLOAD_CODE = "<?=$_SESSION["POST_IMAGE_UPLOAD_CODE"]=GUIDv4();?>";
	var POST_IMAGE_LIST_CODE = "<?=$_SESSION["POST_IMAGE_LIST_CODE"]=GUIDv4();?>";    
</script>