<?php

if (!isset($_SESSION["CONTACT_MESSAGE_CODE"])) {
	$_SESSION["CONTACT_MESSAGE_CODE"] = GUIDv4();
}

if (!isset($_SESSION["GET_SUBCATEGORY_LIST_CODE"])) {
	$_SESSION["GET_SUBCATEGORY_LIST_CODE"] = GUIDv4();
}

if (!isset($_SESSION["FILTER_DATA_CODE"])) {
	$_SESSION["FILTER_DATA_CODE"] = GUIDv4();
}

if (!isset($_SESSION["LOGIN_MASTER_CODE"])) {
	$_SESSION["LOGIN_MASTER_CODE"] = GUIDv4();
}

if (!isset($_SESSION["LOGIN_CODE"])) {
	$_SESSION["LOGIN_CODE"] = GUIDv4();
}

if (!isset($_SESSION["LOGIN_WITH_CAPTCHA_CODE"])) {
	$_SESSION["LOGIN_WITH_CAPTCHA_CODE"] = GUIDv4();
}

if (!isset($_SESSION["REGISTER_CODE"])) {
	$_SESSION["REGISTER_CODE"] = GUIDv4();
}

if (!isset($_SESSION["VISIT_CODE"])) {
	$_SESSION["VISIT_CODE"] = GUIDv4();
}

if (!isset($_SESSION["SEND_OTP_CODE"])) {
	$_SESSION["SEND_OTP_CODE"] = GUIDv4();
}

if (!isset($_SESSION["RECOVER_PASSWORD_CODE"])) {
	$_SESSION["RECOVER_PASSWORD_CODE"] = GUIDv4();
}

?>

<script>
	var CONTACT_MESSAGE_CODE = "<?= $_SESSION["CONTACT_MESSAGE_CODE"] ?>";
	var GET_SUBCATEGORY_LIST_CODE = "<?= $_SESSION["GET_SUBCATEGORY_LIST_CODE"] ?>";
	var FILTER_DATA_CODE = "<?= $_SESSION["FILTER_DATA_CODE"] ?>";
	var LOGIN_MASTER_CODE = "<?= $_SESSION["LOGIN_MASTER_CODE"] ?>";
	var LOGIN_CODE = "<?= $_SESSION["LOGIN_CODE"] ?>";
	var LOGIN_WITH_CAPTCHA_CODE = "<?= $_SESSION["LOGIN_WITH_CAPTCHA_CODE"] ?>";
	var REGISTER_CODE = "<?= $_SESSION["REGISTER_CODE"] ?>";
	var VISIT_CODE = "<?= $_SESSION["VISIT_CODE"] ?>";
	var SEND_OTP_CODE = "<?= $_SESSION["SEND_OTP_CODE"] ?>";
	var RECOVER_PASSWORD_CODE = "<?= $_SESSION["RECOVER_PASSWORD_CODE"] ?>";
</script>